name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Building
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: cd ${{ vars.PROD_PATH }} &&
            pm2 stop televito-parser &&
            git checkout main &&
            git reset --hard &&
            git pull &&
            export PATH=$PATH:/usr/local/go/bin &&
            go build &&
            rm -f 1.log &&
            MYSQL_CONNECTION_STRING="${{ secrets.MYSQL_CONNECTION_STRING }}" pm2 start televito-parser --update-env

