name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: su ${{ vars.USER_NAME }}
            && cd ${{ vars.PROD_PATH }}
            && ls -la
            && git checkout main
            && git reset --hard
            && git pull
            && go build
            && MYSQL_CONNECTION_STRING="${{ secrets.MYSQL_CONNECTION_STRING }}" ./televito-parser



